#!/bin/bash -e

declare -r GENERATOR_NAME=${0/*\//}
declare -r CONF_PREFIX=mirror-port
declare -r CONF_DIR=/etc/conf.d
declare -r BIN_PREFIX=/usr/bin/
declare -r SERVICE_NAME=mirror-port@.service
declare -r DROP_IN_FNAME=mirror-port.conf

declare -r DST_DIR=$1
if [ -z "${DST_DIR}" ]; then
    exit 1
fi

get_mirror_port() {
    local MIRROR_PORT

    if [[ -n "$1" ]]; then
        . ${CONF_DIR}/${CONF_PREFIX}-$1
    else
	. ${CONF_DIR}/${CONF_PREFIX}
    fi

    if [ -z "${MIRROR_PORT}" ]; then
        return 1
    fi

   echo ${MIRROR_PORT}
}

get_unit_preamble() {
cat <<EOF
#
# This drop-in was generated by ${GENERATOR_NAME}.
# Please do not edit this file.
#
[Unit]
EOF
}

if [[ -f ${CONF_DIR}/${CONF_PREFIX} ]]; then
    mirror_port=$(get_mirror_port) || mirror_port='br-mrr'
    mirror_port_esc=$(${BIN_PREFIX}systemd-escape ${mirror_port})
    ${BIN_PREFIX}mkdir -p ${DST_DIR}/${SERVICE_NAME}.d
    (
	get_unit_preamble
        cat <<EOF
Description=Mirroring traffic from %I to ${mirror_port}
SourcePath=${CONF_DIR}/${CONF_PREFIX}
BindsTo=sys-subsystem-net-devices-${mirror_port_esc}.device
After=sys-subsystem-net-devices-${mirror_port_esc}.device
EOF
    ) > ${DST_DIR}/${SERVICE_NAME}.d/${DROP_IN_FNAME}
fi

declare -a CONFIGS
CONFIGS=($(${BIN_PREFIX}find ${CONF_DIR} -maxdepth 1 -type f -name ${CONF_PREFIX}-'*' -printf "%f\n")) || true
CONFIGS=(${CONFIGS[@]#${CONF_PREFIX}-})

for iface in ${CONFIGS[*]}; do
    iface_esc=$(${BIN_PREFIX}systemd-escape --template=${SERVICE_NAME} ${iface})
    mirror_port=$(get_mirror_port ${iface}) || continue
    mirror_port_esc=$(${BIN_PREFIX}systemd-escape ${mirror_port})
    ${BIN_PREFIX}mkdir -p ${DST_DIR}/${iface_esc}.d
    (
	get_unit_preamble
        cat <<EOF
Description=Mirroring traffic from %I to ${mirror_port}
SourcePath=${CONF_DIR}/${CONF_PREFIX}-${iface}
BindsTo=sys-subsystem-net-devices-${mirror_port_esc}.device
After=sys-subsystem-net-devices-${mirror_port_esc}.device
EOF
    ) > ${DST_DIR}/${iface_esc}.d/${DROP_IN_FNAME}
done
